# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14K7-dSsHUCaQlcxxdN1UN6N2JsGUZqQo
"""

!gdown https://drive.google.com/uc?id=15JsVCUxYsSGFRwGhqre0zLpSIg3-jLvO #Downloading zip file from google drive
zip_path = '/content/Cat_Classifier_Images_70-30-20200828T022923Z-001.zip' #Getting the path 
!unzip -q Cat_Classifier_Images_70-30-20200829T163124Z-001.zip #Unzipping the folder
!rm Cat_Classifier_Images_70-30-20200829T163124Z-001.zip #Removing the zip folder
import os #Imported required libraries for this step
import pdb
import cv2
import operator
from PIL import Image
os.mkdir("Training-70-30") #making the new Training and testing folders
os.mkdir("Testing-70-30")
dirs = ["Domino", "Stormy"] #Making the names for the subdirec
pardirs = ["/content/Training-70-30", "/content/Testing-70-30"]
for pardir in pardirs:
  for dir in dirs:
    path = os.path.join(pardir, dir)
    os.mkdir(path)
datadir1 = "/content/Cat_Classifier_Images_70-30 /Train/Domino"
datadir2 = "/content/Cat_Classifier_Images_70-30 /Train/Stormy"
datadir3 = "/content/Cat_Classifier_Images_70-30 /Test/Domino"
datadir4 = "/content/Cat_Classifier_Images_70-30 /Test/Stormy"
filelist1 = sorted(os.listdir(datadir1), key = lambda fname: int(fname.split("_")[0][-4:]))
filelist2 = sorted(os.listdir(datadir2), key = lambda fname: int(fname.split("_")[0][-4:]))
filelist3 = sorted(os.listdir(datadir3), key = lambda fname: int(fname.split("_")[0][-4:]))
filelist4 = sorted(os.listdir(datadir4), key = lambda fname: int(fname.split("_")[0][-4:]))
datadirs1 = [filelist1, filelist2, filelist3, filelist4]
inc = 0
for filelist in datadirs1:
  i = 0
  for fil in filelist:
    if inc == 0:
      path = "/content/Cat_Classifier_Images_70-30 /Train/Domino/" + fil
      i += 1
      img = cv2.imread(path)
      imgResized = cv2.resize(img, (96, 128))
      cv2.imwrite('/content/Training-70-30/Domino/DominoTR%02i.jpg' %i, imgResized)
    elif inc == 1:
      path = "/content/Cat_Classifier_Images_70-30 /Train/Stormy/" + fil
      i += 1
      img = cv2.imread(path)
      imgResized = cv2.resize(img, (96, 128))
      cv2.imwrite('/content/Training-70-30/Stormy/StormyTR%02i.jpg' %i, imgResized)
    elif inc == 2:
      path = "/content/Cat_Classifier_Images_70-30 /Test/Domino/" + fil
      i += 1
      img = cv2.imread(path)
      imgResized = cv2.resize(img, (96, 128))
      cv2.imwrite('/content/Testing-70-30/Domino/DominoTS%02i.jpg' %i, imgResized)
    else:
      path = "/content/Cat_Classifier_Images_70-30 /Test/Stormy/" + fil
      i += 1
      img = cv2.imread(path)
      imgResized = cv2.resize(img, (96, 128))
      cv2.imwrite('/content/Testing-70-30/Stormy/StormyTS%02i.jpg' %i, imgResized)
  inc += 1