# -*- coding: utf-8 -*-
"""ImageClassfierTestCode

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gVPLuR535uiNBTC0tOEtPPLhQUXNFF2m
"""

from keras.preprocessing import image
import cv2
exp_img = cv2.imread('/content/Testing-70-30/Stormy/StormyTS06.jpg')
exp2_img = cv2.resize(exp_img, (64, 48))
exp2_img = image.img_to_array(exp2_img)
exp2_img = np.expand_dims(exp2_img, axis = 0)
result = classifier.predict(exp2_img)
if result[0][0] == 1:
  print ('This image is Domino')
else:
  print ("This image is Stormy")